name: cocoapods-publish

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Release version (e.g. "1.0.0")'
          required: true
          type: string

# https://github.com/actions/runner-images/?tab=readme-ov-file#available-images
jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Push to Cocoapods trunk
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        mkdir -p tmp

        # Update podspec
        jq --arg VERSION "${{ inputs.version }}" '. | .version |= $VERSION | .source.tag |= $VERSION' PodVersionTest.podspec.json > tmp/PodVersionTest.podspec.json

        # Lint podspec
        pod spec lint tmp/PodVersionTest.podspec.json

        # Publish podspec
        pod trunk push tmp/PodVersionTest.podspec.json

        # Clean up
        rm -r tmp
