name: cocoapods-publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

# https://github.com/actions/runner-images/?tab=readme-ov-file#available-images
jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Push to Cocoapods trunk
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        POD_VERSION: ${{ github.ref_name }}
      run: |
        mkdir -p tmp

        # Update podspec
        jq --arg VERSION "$POD_VERSION" '. | .version |= $VERSION | .source.tag |= $VERSION' PodVersionTest.podspec.json > tmp/PodVersionTest.podspec.json

        # Lint podspec
        pod spec lint tmp/PodVersionTest.podspec.json

        # Publish podspec
        pod trunk push tmp/PodVersionTest.podspec.json

        # Clean up
        rm -r tmp
